name: CI

on:
  push:
    branch: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm i
    - run: npm run lint
    - run: npm test -- --coverage
    - run: npm run doc
    - run: npx codecov
    - name: Documetation
      uses: peaceiris/actions-gh-pages@v3
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out